"""first-commit

Revision ID: 0d7efec71d4f
Revises: 
Create Date: 2024-12-31 20:48:22.374406

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '0d7efec71d4f'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('nickname', sa.String(), nullable=False),
    sa.Column('hashed_password', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_uuid'), 'user', ['uuid'], unique=True)
    op.create_table('category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.CheckConstraint("(color IS NULL OR color ~* '^#[a-f0-9]{6}$')", name='check_color_hex'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_category_uuid'), 'category', ['uuid'], unique=True)
    op.create_table('sub_category',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('color', sa.String(length=7), nullable=True),
    sa.CheckConstraint("(color IS NULL OR color ~* '^#[a-f0-9]{6}$')", name='check_color_hex'),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_sub_category_uuid'), 'sub_category', ['uuid'], unique=True)
    op.create_table('time_range_event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.UUID(), server_default=sa.text('gen_random_uuid()'), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('category_id', sa.Integer(), nullable=True),
    sa.Column('sub_category_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('description', sa.String(), nullable=True),
    sa.Column('start_time', sa.DateTime(timezone=True), nullable=False),
    sa.Column('end_time', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['category_id'], ['category.id'], ),
    sa.ForeignKeyConstraint(['sub_category_id'], ['sub_category.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_time_range_event_uuid'), 'time_range_event', ['uuid'], unique=True)
    op.create_index('unique_active_time_range_event_per_user', 'time_range_event', ['user_id'], unique=True, postgresql_where=sa.text('end_time IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_active_time_range_event_per_user', table_name='time_range_event', postgresql_where=sa.text('end_time IS NULL'))
    op.drop_index(op.f('ix_time_range_event_uuid'), table_name='time_range_event')
    op.drop_table('time_range_event')
    op.drop_index(op.f('ix_sub_category_uuid'), table_name='sub_category')
    op.drop_table('sub_category')
    op.drop_index(op.f('ix_category_uuid'), table_name='category')
    op.drop_table('category')
    op.drop_index(op.f('ix_user_uuid'), table_name='user')
    op.drop_table('user')
    # ### end Alembic commands ###
