"""timer_range view

Revision ID: c88e4ff63673
Revises: 0d7efec71d4f
Create Date: 2024-12-31 21:10:53.313517

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = 'c88e4ff63673'
down_revision: Union[str, None] = '0d7efec71d4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_time_range_event_not_deleted = PGView(
        schema="public",
        signature="time_range_event_not_deleted",
        definition='SELECT id, uuid, user_id, category_id, sub_category_id, title, description, start_time, end_time \nFROM time_range_event \nWHERE time_range_event.deleted_at IS NULL'
    )
    op.create_entity(public_time_range_event_not_deleted) # type: ignore[attr-defined]

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_time_range_event_not_deleted = PGView(
        schema="public",
        signature="time_range_event_not_deleted",
        definition='SELECT id, uuid, user_id, category_id, sub_category_id, title, description, start_time, end_time \nFROM time_range_event \nWHERE time_range_event.deleted_at IS NULL'
    )
    op.drop_entity(public_time_range_event_not_deleted) # type: ignore[attr-defined]

    # ### end Alembic commands ###
