"""timer event constrain

Revision ID: dcd2eb6afe4d
Revises: f60c78058434
Create Date: 2024-12-23 21:50:29.093416

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dcd2eb6afe4d'
down_revision: Union[str, None] = 'f60c78058434'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('unique_active_time_range_event_per_user', 'time_range_event', ['user_id'], unique=True, postgresql_where=sa.text('end_time IS NULL'))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('unique_active_time_range_event_per_user', table_name='time_range_event', postgresql_where=sa.text('end_time IS NULL'))
    # ### end Alembic commands ###
