"""view and functions test

Revision ID: deda4dea69be
Revises: a9368478f5c4
Create Date: 2024-08-31 20:55:10.271209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from alembic_utils.pg_view import PGView
from sqlalchemy import text as sql_text

# revision identifiers, used by Alembic.
revision: str = '46a916801fd8'
down_revision: Union[str, None] = 'a9368478f5c4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_time_range_event_not_deleted = PGView(
        schema="public",
        signature="time_range_event_not_deleted",
        definition='SELECT id, uuid, user_id, category_id, sub_category_id, title, description, start_time, end_time \nFROM time_range_event \nWHERE time_range_event.deleted_at IS NULL'
    )
    op.create_entity(public_time_range_event_not_deleted)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    public_time_range_event_not_deleted = PGView(
        schema="public",
        signature="time_range_event_not_deleted",
        definition='SELECT id, uuid, user_id, category_id, sub_category_id, title, description, start_time, end_time \nFROM time_range_event \nWHERE time_range_event.deleted_at IS NULL'
    )
    op.drop_entity(public_time_range_event_not_deleted)

    # ### end Alembic commands ###
